### ISSUE TITLE
A buyer should be able to contact the seller through email

### ISSUE THREAD

**Issue by David-Liu-G** [ECSE428-MCGILL/backend#8]
# Story
Buyer wants to contact a seller through the website in order to buy a book.
## Normal Scenario

- Buyer is in the page of a posting he is interested to buy.
- Buyer clicks on “Contact seller”.
- System displays a dialogue box.
- Buyer enters a message in the dialogue box..
- Buyer clicks on  “Send”.
- System sends  a message with the content of the dialogue box to the user. 

## Alternate Scenario

- Buyer is in the  page of a posting he is interested to buy.
- Buyer clicks on the seller’s username on the post.
- The system redirects the buyer to the seller’s profile page.
- Buyer clicks on“Send Message”.
- System displays a dialogue box.
- Buyer enters a message in the dialogue box..
- Buyer clicks on  “Send”.
- System sends  a message with the content of the dialogue box to the user. 

## Error Scenario

- Buyer is in the page of a posting he is interested to buy.
- Buyer clicks on “Contact seller”.
- System displays a dialogue box.
- Buyer does not enter a message in the dialogue box.
- Buyer clicks on  “Send”.
- System does not send a message to the seller of the book posting.
- System displays an error message asking the buyer to enter a non empty message.

**Comment by AndresFelipeRG** [comment]
I did some research on this, and it could be more easy to work with gmail emails.
